import { createContext, useState, useContext, useEffect, ReactNode } from 'react';

type Language = 'en' | 'kn' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'welcome': 'Welcome',
    'home_page': 'Home Page',
    'content_area': 'Content Area',
    'no_content_available': 'No content is available at the moment. Please contact your administrator.',
    'loading': 'Loading...',
    'user_management': 'User Management',
    'add_new_user': 'Add New User',
    'quiz': 'Quiz',
    'submit_answer': 'Submit Answer',
    'next_question': 'Next Question',
    'close': 'Close',
    'correct': 'Correct!',
    'incorrect_answer_message': 'Incorrect. The correct answer is:',
    'quiz_results': 'Quiz Results',
    'you_answered': 'You answered',
    'out_of': 'out of',
    'questions_correctly': 'questions correctly',
    'close_quiz': 'Close Quiz',
    'access_denied': 'Access Denied',
    'permission_denied_message': 'You do not have permission to view this page.',
    'content_paths': 'Content Paths',
    'add_new_content_path': 'Add New Content Path',
    'existing_content_paths': 'Existing Content Paths',
    'id': 'ID',
    'path': 'Path',
    'active': 'Active',
    'actions': 'Actions',
    'edit': 'Edit',
    'delete': 'Delete',
    'no_content_paths_found': 'No content paths found.',
    'settings': 'Settings',
    'select_language': 'Select Language',
    'english': 'English',
    'kannada': 'Kannada',
    'hindi': 'Hindi',
    'save': 'Save',
    'dashboard': 'Dashboard',
    'users': 'Users',
    'content': 'Content',
    'quizzes': 'Quizzes',
    'login': 'Login',
    'username': 'Username',
    'password': 'Password',
    'logout': 'Logout',
    'new_activation': 'New Activation',
    'reactivation': 'Reactivation',
    'activation_key': 'Activation Key',
    'activate': 'Activate',
    'back_to_login': 'Back to Login',
    'enter_activation_key': 'Enter your activation key to reactivate the application.',
    'reactivate': 'Reactivate',
    'application_activated_success': 'Application activated successfully!',
    'activation_failed': 'Activation failed.',
    'application_reactivated_success': 'Application reactivated successfully!',
    'reactivation_failed': 'Reactivation failed.',
    'loading_content_path_status': 'Loading content path status...',
    'back': 'Back',
    'no_active_content_path_set': 'No active content path set',
    'set_active_content_path_message': 'Please set an active content path to access the content management features.',
    'go_to_content_path_settings': 'Go to Content Path Settings',
    'loading_content_paths': 'Loading content paths...',
    'failed_to_load_content_paths': 'Failed to load content paths.',
    'access_denied_admin_message': 'Access Denied: Only administrators can view this page.',
    'select_content_folder': 'Select Content Folder',
    'no_directory_selected': 'No directory selected',
    'browse': 'Browse',
    'add_path': 'Add Path',
    'please_select_directory_first': 'Please select a directory first.',
    'content_path_saved_success': 'Content path saved and set as active successfully!',
    'error_saving_content_path': 'Error saving content path:',
    'content_path_set_active_success': 'Content path with ID {{id}} set as active!',
    'error_setting_content_path_active': 'Error setting content path active:',
    'confirm_delete_content_path': 'Are you sure you want to delete this content path?',
    'content_path_deleted_success': 'Content path with ID {{id}} deleted successfully.',
    'error_deleting_content_path': 'Error deleting content path:',
    'status': 'Status',
    'active_status': 'Active',
    'inactive_status': 'Inactive',
    'set_active': 'Set Active',
    'delete_button': 'Delete',
    'login_failed_role': 'Login failed: Could not retrieve user role.',
    'activation_reactivation': 'Activation / Reactivation',
    'back_button': 'Back',
    'activate_recheck': 'Activate / Recheck',
    'activation_title': 'Activation',
    'institution_name': 'Institution Name',
    'head_of_institution': 'Head of Institution',
    'mobile_no': 'Mobile No',
    'serial_number': 'Serial Number',
    'product_key': 'Product Key',
    'product_activation_panel': 'Product Activation Panel',
    'have_activation_key': 'Have Activation Key',
    'register_for_activation_key': 'Register for Activation Key',
    'passwords_do_not_match': 'Passwords do not match!',
    'edit_user': 'Edit User',
    'add_new_user_form': 'Add New User',
    'name': 'Name',
    'enter_name': 'Enter name',
    'enter_password': 'Enter password',
    'confirm_password': 'Confirm Password',
    're_enter_password': 'Re-enter password',
    'role': 'Role',
    'admin_role': 'Admin',
    'user_role': 'User',
    'cancel': 'Cancel',
    'submit': 'Submit',
  },
  kn: {
    'welcome': 'ಸ್ವಾಗತ',
    'home_page': 'ಮುಖಪುಟ',
    'content_area': 'ವಿಷಯ ಕ್ಷೇತ್ರ',
    'no_content_available': 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ವಿಷಯ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ನಿರ್ವಾಹಕರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'user_management': 'ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ',
    'add_new_user': 'ಹೊಸ ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ',
    'quiz': 'ರಸಪ್ರಶ್ನೆ',
    'submit_answer': 'ಉತ್ತರವನ್ನು ಸಲ್ಲಿಸಿ',
    'next_question': 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
    'close': 'ಮುಚ್ಚಿ',
    'correct': 'ಸರಿಯಾಗಿದೆ!',
    'incorrect_answer_message': 'ತಪ್ಪಾಗಿದೆ. ಸರಿಯಾದ ಉತ್ತರ:',
    'quiz_results': 'ರಸಪ್ರಶ್ನೆ ಫಲಿತಾಂಶಗಳು',
    'you_answered': 'ನೀವು ಉತ್ತರಿಸಿದ್ದೀರಿ',
    'out_of': 'ಒಟ್ಟು',
    'questions_correctly': 'ಪ್ರಶ್ನೆಗಳಿಗೆ ಸರಿಯಾಗಿ',
    'close_quiz': 'ರಸಪ್ರಶ್ನೆ ಮುಚ್ಚಿ',
    'access_denied': 'ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ',
    'permission_denied_message': 'ಈ ಪುಟವನ್ನು ವೀಕ್ಷಿಸಲು ನಿಮಗೆ ಅನುಮತಿ ಇಲ್ಲ.',
    'content_paths': 'ವಿಷಯ ಮಾರ್ಗಗಳು',
    'add_new_content_path': 'ಹೊಸ ವಿಷಯ ಮಾರ್ಗವನ್ನು ಸೇರಿಸಿ',
    'existing_content_paths': 'ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ವಿಷಯ ಮಾರ್ಗಗಳು',
    'id': 'ಐಡಿ',
    'path': 'ಮಾರ್ಗ',
    'active': 'ಸಕ್ರಿಯ',
    'actions': 'ಕ್ರಿಯೆಗಳು',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'delete': 'ಅಳಿಸಿ',
    'no_content_paths_found': 'ಯಾವುದೇ ವಿಷಯ ಮಾರ್ಗಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    'english': 'ಇಂಗ್ಲಿಷ್',
    'kannada': 'ಕನ್ನಡ',
    'hindi': 'ಹಿಂದಿ',
    'save': 'ಉಳಿಸಿ',
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'users': 'ಬಳಕೆದಾರರು',
    'content': 'ವಿಷಯ',
    'quizzes': 'ರಸಪ್ರಶ್ನೆಗಳು',
    'login': 'ಲಾಗ್ ಇನ್',
    'username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'password': 'ಪಾಸ್‌ವರ್ಡ್',
    'logout': 'ಲಾಗ್ ಔಟ್',
    'new_activation': 'ಹೊಸ ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ',
    'reactivation': 'ಮರು-ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ',
    'activation_key': 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ಕೀ',
    'activate': 'ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'back_to_login': 'ಲಾಗ್ ಇನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'enter_activation_key': 'ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಮರು-ಸಕ್ರಿಯಗೊಳಿಸಲು ನಿಮ್ಮ ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ಕೀ ನಮೂದಿಸಿ.',
    'reactivate': 'ಮರು-ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'application_activated_success': 'ಅಪ್ಲಿಕೇಶನ್ ಯಶಸ್ವಿಯಾಗಿ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ!',
    'activation_failed': 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ.',
    'application_reactivated_success': 'ಅಪ್ಲಿಕೇಶನ್ ಯಶಸ್ವಿಯಾಗಿ ಮರು-ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ!',
    'reactivation_failed': 'ಮರು-ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ.',
    'loading_content_path_status': 'ವಿಷಯ ಮಾರ್ಗ ಸ್ಥಿತಿಯನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'back': 'ಹಿಂದೆ',
    'no_active_content_path_set': 'ಯಾವುದೇ ಸಕ್ರಿಯ ವಿಷಯ ಮಾರ್ಗವನ್ನು ಹೊಂದಿಸಲಾಗಿಲ್ಲ',
    'set_active_content_path_message': 'ವಿಷಯ ನಿರ್ವಹಣಾ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ದಯವಿಟ್ಟು ಸಕ್ರಿಯ ವಿಷಯ ಮಾರ್ಗವನ್ನು ಹೊಂದಿಸಿ.',
    'go_to_content_path_settings': 'ವಿಷಯ ಮಾರ್ಗ ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಗೆ ಹೋಗಿ',
    'loading_content_paths': 'ವಿಷಯ ಮಾರ್ಗಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'failed_to_load_content_paths': 'ವಿಷಯ ಮಾರ್ಗಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.',
    'access_denied_admin_message': 'ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ: ನಿರ್ವಾಹಕರು ಮಾತ್ರ ಈ ಪುಟವನ್ನು ವೀಕ್ಷಿಸಬಹುದು.',
    'select_content_folder': 'ವಿಷಯ ಫೋಲ್ಡರ್ ಆಯ್ಕೆಮಾಡಿ',
    'no_directory_selected': 'ಯಾವುದೇ ಡೈರೆಕ್ಟರಿ ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ',
    'browse': 'ಬ್ರೌಸ್ ಮಾಡಿ',
    'add_path': 'ಮಾರ್ಗವನ್ನು ಸೇರಿಸಿ',
    'please_select_directory_first': 'ದಯವಿಟ್ಟು ಮೊದಲು ಡೈರೆಕ್ಟರಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'content_path_saved_success': 'ವಿಷಯ ಮಾರ್ಗವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ಸಕ್ರಿಯ ಎಂದು ಹೊಂದಿಸಲಾಗಿದೆ!',
    'error_saving_content_path': 'ವಿಷಯ ಮಾರ್ಗವನ್ನು ಉಳಿಸುವಲ್ಲಿ ದೋಷ:',
    'content_path_set_active_success': 'ಐಡಿ {{id}} ನ ವಿಷಯ ಮಾರ್ಗವನ್ನು ಸಕ್ರಿಯ ಎಂದು ಹೊಂದಿಸಲಾಗಿದೆ!',
    'error_setting_content_path_active': 'ವಿಷಯ ಮಾರ್ಗವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸುವಲ್ಲಿ ದೋಷ:',
    'confirm_delete_content_path': 'ನೀವು ಈ ವಿಷಯ ಮಾರ್ಗವನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿರುವಿರಾ?',
    'content_path_deleted_success': 'ಐಡಿ {{id}} ನ ವಿಷಯ ಮಾರ್ಗವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ.',
    'error_deleting_content_path': 'ವಿಷಯ ಮಾರ್ಗವನ್ನು ಅಳಿಸುವಲ್ಲಿ ದೋಷ:',
    'status': 'ಸ್ಥಿತಿ',
    'active_status': 'ಸಕ್ರಿಯ',
    'inactive_status': 'ನಿಷ್ಕ್ರಿಯ',
    'set_active': 'ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'delete_button': 'ಅಳಿಸಿ',
    'login_failed_role': 'ಲಾಗ್ ಇನ್ ವಿಫಲವಾಗಿದೆ: ಬಳಕೆದಾರರ ಪಾತ್ರವನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    'activation_reactivation': 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ / ಮರು-ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ',
    'back_button': 'ಹಿಂದೆ',
    'activate_recheck': 'ಸಕ್ರಿಯಗೊಳಿಸಿ / ಮರು-ಪರಿಶೀಲಿಸಿ',
    'activation_title': 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ',
    'institution_name': 'ಸಂಸ್ಥೆಯ ಹೆಸರು',
    'head_of_institution': 'ಸಂಸ್ಥೆಯ ಮುಖ್ಯಸ್ಥರು',
    'mobile_no': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'serial_number': 'ಸರಣಿ ಸಂಖ್ಯೆ',
    'product_key': 'ಉತ್ಪನ್ನ ಕೀ',
    'product_activation_panel': 'ಉತ್ಪನ್ನ ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ಫಲಕ',
    'have_activation_key': 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ಕೀ ಇದೆ',
    'register_for_activation_key': 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ಕೀಗಾಗಿ ನೋಂದಾಯಿಸಿ',
    'passwords_do_not_match': 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ!',
    'edit_user': 'ಬಳಕೆದಾರರನ್ನು ಸಂಪಾದಿಸಿ',
    'add_new_user_form': 'ಹೊಸ ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ',
    'name': 'ಹೆಸರು',
    'enter_name': 'ಹೆಸರು ನಮೂದಿಸಿ',
    'enter_password': 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    're_enter_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರು-ನಮೂದಿಸಿ',
    'role': 'ಪಾತ್ರ',
    'admin_role': 'ನಿರ್ವಾಹಕ',
    'user_role': 'ಬಳಕೆದಾರ',
    'cancel': 'ರದ್ದುಮಾಡು',
    'submit': 'ಸಲ್ಲಿಸಿ',
  },
  hi: {
    'welcome': 'स्वागत हे',
    'home_page': 'मुख पृष्ठ',
    'content_area': 'सामग्री क्षेत्र',
    'no_content_available': 'वर्तमान में कोई सामग्री उपलब्ध नहीं है। कृपया अपने व्यवस्थापक से संपर्क करें।',
    'loading': 'लोड हो रहा है...',
    'user_management': 'उपयोगकर्ता प्रबंधन',
    'add_new_user': 'नया उपयोगकर्ता जोड़ें',
    'quiz': 'प्रश्नोत्तरी',
    'submit_answer': 'उत्तर सबमिट करें',
    'next_question': 'अगला प्रश्न',
    'close': 'बंद करें',
    'correct': 'सही!',
    'incorrect_answer_message': 'गलत। सही उत्तर है:',
    'quiz_results': 'क्विज़ परिणाम',
    'you_answered': 'आपने जवाब दिया',
    'out_of': 'में से',
    'questions_correctly': 'प्रश्नों का सही उत्तर दिया',
    'close_quiz': 'क्विज़ बंद करें',
    'access_denied': 'पहुँच अस्वीकृत',
    'permission_denied_message': 'आपको इस पृष्ठ को देखने की अनुमति नहीं है।',
    'content_paths': 'सामग्री पथ',
    'add_new_content_path': 'नया सामग्री पथ जोड़ें',
    'existing_content_paths': 'मौजूदा सामग्री पथ',
    'id': 'आईडी',
    'path': 'पथ',
    'active': 'सक्रिय',
    'actions': 'कार्य',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'no_content_paths_found': 'कोई सामग्री पथ नहीं मिला।',
    'settings': 'सेटिंग्स',
    'select_language': 'भाषा का चयन करें',
    'english': 'अंग्रेजी',
    'kannada': 'कन्नड़',
    'hindi': 'हिंदी',
    'save': 'सहेजें',
    'dashboard': 'डैशबोर्ड',
    'users': 'उपयोगकर्ता',
    'content': 'सामग्री',
    'quizzes': 'प्रश्नोत्तरी',
    'login': 'लॉग इन करें',
    'username': 'उपयोगकर्ता नाम',
    'password': 'पासवर्ड',
    'logout': 'लॉग आउट',
    'new_activation': 'नया सक्रियण',
    'reactivation': 'पुनः सक्रियण',
    'activation_key': 'सक्रियण कुंजी',
    'activate': 'सक्रिय करें',
    'back_to_login': 'लॉग इन पर वापस जाएं',
    'enter_activation_key': 'एप्लिकेशन को पुनः सक्रिय करने के लिए अपनी सक्रियण कुंजी दर्ज करें।',
    'reactivate': 'पुनः सक्रिय करें',
    'application_activated_success': 'एप्लिकेशन सफलतापूर्वक सक्रिय हो गया!',
    'activation_failed': 'सक्रियण विफल रहा।',
    'application_reactivated_success': 'एप्लिकेशन सफलतापूर्वक पुनः सक्रिय हो गया!',
    'reactivation_failed': 'पुनः सक्रियण विफल रहा।',
    'loading_content_path_status': 'सामग्री पथ स्थिति लोड हो रही है...',
    'back': 'वापस',
    'no_active_content_path_set': 'कोई सक्रिय सामग्री पथ सेट नहीं है',
    'set_active_content_path_message': 'सामग्री प्रबंधन सुविधाओं तक पहुंचने के लिए कृपया एक सक्रिय सामग्री पथ सेट करें।',
    'go_to_content_path_settings': 'सामग्री पथ सेटिंग्स पर जाएं',
    'loading_content_paths': 'सामग्री पथ लोड हो रहे हैं...',
    'failed_to_load_content_paths': 'सामग्री पथ लोड करने में विफल।',
    'access_denied_admin_message': 'पहुंच अस्वीकृत: केवल व्यवस्थापक ही इस पृष्ठ को देख सकते हैं।',
    'select_content_folder': 'सामग्री फ़ोल्डर चुनें',
    'no_directory_selected': 'कोई निर्देशिका नहीं चुनी गई',
    'browse': 'ब्राउज़ करें',
    'add_path': 'पथ जोड़ें',
    'please_select_directory_first': 'कृपया पहले एक निर्देशिका चुनें।',
    'content_path_saved_success': 'सामग्री पथ सफलतापूर्वक सहेजा गया और सक्रिय के रूप में सेट किया गया!',
    'error_saving_content_path': 'सामग्री पथ सहेजने में त्रुटि:',
    'content_path_set_active_success': 'आईडी {{id}} के साथ सामग्री पथ सक्रिय के रूप में सेट किया गया!',
    'error_setting_content_path_active': 'सामग्री पथ सक्रिय करने में त्रुटि:',
    'confirm_delete_content_path': 'क्या आप वाकई इस सामग्री पथ को हटाना चाहते हैं?',
    'content_path_deleted_success': 'आईडी {{id}} के साथ सामग्री पथ सफलतापूर्वक हटा दिया गया।',
    'error_deleting_content_path': 'सामग्री पथ हटाने में त्रुटि:',
    'status': 'स्थिति',
    'active_status': 'सक्रिय',
    'inactive_status': 'निष्क्रिय',
    'set_active': 'सक्रिय करें',
    'delete_button': 'हटाएं',
    'login_failed_role': 'लॉगिन विफल रहा: उपयोगकर्ता भूमिका प्राप्त नहीं कर सका।',
    'activation_reactivation': 'सक्रियण / पुनः सक्रियण',
    'back_button': 'वापस',
    'activate_recheck': 'सक्रिय करें / पुनः जांचें',
    'activation_title': 'सक्रियण',
    'institution_name': 'संस्थान का नाम',
    'head_of_institution': 'संस्थान के प्रमुख',
    'mobile_no': 'मोबाइल नंबर',
    'serial_number': 'क्रम संख्या',
    'product_key': 'उत्पाद कुंजी',
    'product_activation_panel': 'उत्पाद सक्रियण पैनल',
    'have_activation_key': 'सक्रियण कुंजी है',
    'register_for_activation_key': 'सक्रियण कुंजी के लिए पंजीकरण करें',
    'passwords_do_not_match': 'पासवर्ड मेल नहीं खाते!',
    'edit_user': 'उपयोगकर्ता संपादित करें',
    'add_new_user_form': 'नया उपयोगकर्ता जोड़ें',
    'name': 'नाम',
    'enter_name': 'नाम दर्ज करें',
    'enter_password': 'पासवर्ड दर्ज करें',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    're_enter_password': 'पासवर्ड पुनः दर्ज करें',
    'role': 'भूमिका',
    'admin_role': 'व्यवस्थापक',
    'user_role': 'उपयोगकर्ता',
    'cancel': 'रद्द करें',
    'submit': 'प्रस्तुत करें',
  },
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 